language: node_js
node_js:
    - "10.0"
scripts:
    - echo "Deploying to firebase"
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --token 1//0f_S5eZ0uUZ4sCgYIARAAGA8SNwF-L9IrSQA8NchP2f6OdAC7BdE1ljQUuQBDp2PEW0kB6QfwI9gNNccqPGwdOF6cRk-Ccyx6Dkg