language: node_js
node_js:
    - "10.10.0"
scripts:
    - echo "Deploying to firebase"
    - npm install
    - npm run build
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --project $PROJECT_ID --token $FIREBASE_TOKEN
